<?php

header('Content-Type: text/html; charset=UTF-8');

echo '<!DOCTYPE html>'
    .'<html>'
        .'<head>'
            .'<title>Bubbles</title>'
            .'<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />'
            .'<meta name="viewport" content="width=device-width, user-scalable=no" />'
            .'<link rel="stylesheet" type="text/css" href="js/Main.css" />'
            .'<link rel="stylesheet" type="text/css" href="js/MainPanel.css" />'
        .'</head>'
        .'<body>'
            .'<script type="text/javascript" src="js/Background.js"></script>'
            .'<script type="text/javascript" src="js/BlurCanvas.js"></script>'
            .'<script type="text/javascript" src="js/BreakingBubble.js"></script>'
            .'<script type="text/javascript" src="js/BreakingCanvas.js"></script>'
            .'<script type="text/javascript" src="js/Collide.js"></script>'
            .'<script type="text/javascript" src="js/FallingCanvas.js"></script>'
            .'<script type="text/javascript" src="js/FallingBubble.js"></script>'
            .'<script type="text/javascript" src="js/MainPanel.js"></script>'
            .'<script type="text/javascript" src="js/MovingBubble.js"></script>'
            .'<script type="text/javascript" src="js/MovingCanvas.js"></script>'
            .'<script type="text/javascript" src="js/Neighbors.js"></script>'
            .'<script type="text/javascript" src="js/NextBubble.js"></script>'
            .'<script type="text/javascript" src="js/Orphans.js"></script>'
            .'<script type="text/javascript" src="js/RandomXY.js"></script>'
            .'<script type="text/javascript" src="js/StillBubble.js"></script>'
            .'<script type="text/javascript" src="js/StillCanvas.js"></script>'
            .'<script type="text/javascript" src="js/BubbleShape/Blue.js"></script>'
            .'<script type="text/javascript" src="js/BubbleShape/Green.js"></script>'
            .'<script type="text/javascript" src="js/BubbleShape/Random.js"></script>'
            .'<script type="text/javascript" src="js/BubbleShape/Red.js"></script>'
            .'<script type="text/javascript" src="js/BubbleShape/Violet.js"></script>'
            .'<script type="text/javascript" src="js/BubbleShape/White.js"></script>'
            .'<script type="text/javascript" src="js/BubbleShape/Yellow.js"></script>'
            .'<script type="text/javascript" src="js/Main.js"></script>'
        .'</body>'
    .'</html>';
